"use client";
import React, { Fragment } from "react";
import type { Metadata } from "next";
import { AppProvider, type Navigation } from "@toolpad/core/AppProvider";
import { DashboardLayout } from "@toolpad/core/DashboardLayout";
import { useGetAllProjects } from "@/hooks/query/use-project-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = useGetAllProjects({
    offset: 0,
  });
  const favouriteProjects = (data ?? []).filter(
    (project) => project.isFavorite
  );
  const NAVIGATION: Navigation = [
    {
      kind: "header",
      title: "Favorite Projects",
    },
    ...favouriteProjects.map((project) => ({
      segment: `projects/details/${project.id}`,
      title: project.name,
    })),
  ];
  return (
    <Fragment>
      <AppProvider
        navigation={NAVIGATION}
        branding={{ title: "Project", logo: "" }}
        {...(process.env.NODE_ENV === "development" && { window })}
      >
        <DashboardLayout disableCollapsibleSidebar sx={{ padding: 5 }}>
          {children}
        </DashboardLayout>
      </AppProvider>
    </Fragment>
  );
}
